# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chasing Theta
#email: mchung.92@gmail.com
description: Perpetual student, recovering hippie. A public record of personal thoughts related to tech, learning, and wellness. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#socials
#twitter_username: chasingtheta
#github_username: hellochmi

social:
  name: Michelle Chung
  links:
    - https://github.com/hellochmi
    - https://linkedin.com/in/ouyi-cs
    - https://twitter.com/chasingtheta

social_media:
  - { media_name: GitHub, fa_icon: fa-github-square, profile_link: "https://github.com/hellochmi" }
  - { media_name: LinkedIn, fa_icon: fa-linkedin-square, profile_link: "https://www.linkedin.com/in/michelle-chung-2586846b/" }
  - { media_name: Twitter, fa_icon: twitter-square, profile_link: "https://twitter.com/chasingtheta" }
  
# Build settings
theme: minima

# generate social links in footer
#social_links:
#  twitter: jekyllrb
#  github:  jekyll
  
# Plug-ins
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
